# Конфигурация шахты
mine:
  name: "<#FFFF55>Золотая Шахта"
  world: "world"
  timer_interval: 300
  phases:
    - name: "<green>Легкая фаза"
      display_name: "<green>Легкая"
      spawns:
        STONE: 0.7
        COAL_ORE: 0.2
        IRON_ORE: 0.1
    - name: "<yellow>Средняя фаза"
      display_name: "<yellow>Средняя"
      spawns:
        STONE: 0.6
        IRON_ORE: 0.2
        GOLD_ORE: 0.1
        DIAMOND_ORE: 0.05
        EMERALD_ORE: 0.05
# Конфигурация скупщика
seller:
  items:
    COAL:
      material: COAL
      price: 10
      display_name: "<gray>Уголь"
      lore:
        - "<white>Цена: <green>$<price>"
        - "<white>Множитель: <green><multiplier>x"
    IRON_INGOT:
      material: IRON_INGOT
      price: 50
      display_name: "<white>Железный слиток"
      lore:
        - "<white>Цена: <green>$<price>"
        - "<white>Множитель: <green><multiplier>x"
    GOLD_INGOT:
      material: GOLD_INGOT
      price: 100
      display_name: "<yellow>Золотой слиток"
      lore:
        - "<white>Цена: <green>$<price>"
        - "<white>Множитель: <green><multiplier>x"
    DIAMOND:
      material: DIAMOND
      price: 200
      display_name: "<aqua>Алмаз"
      lore:
        - "<white>Цена: <green>$<price>"
        - "<white>Множитель: <green><multiplier>x"
# Конфигурация квестов
quests:
  - id: mine_coal
    name: "<green>Добыча угля"
    description: "<white>Добудьте 64 угля в шахте."
    material: COAL
    amount: 64
    reward:
      money: 500
      experience: 100
      commands:
        - "give %player% diamond 1"
  - id: mine_iron
    name: "<white>Добыча железа"
    description: "<white>Добудьте 32 железной руды в шахте."
    material: IRON_ORE
    amount: 32
    reward:
      money: 1000
      experience: 200
      commands:
        - "give %player% emerald 1"
# Конфигурация множителя наград
reward_multiplier:
  base: 1.0
  per_quest: 0.1
  max: 2.0